#Лабораторна робота 1
###Студента групи МІТ-31 (підгрупа 2)
###Луніна Леоніда Олександровича

##Завдання
1. NumPy (створити набір даних (розмір за власним рішенням), провести CRUD операції над даними (скаляр, вектор, матриця)). Використати arange, random.
2. Pandas (створити dataframe різними способами, провести маніпуляції з даними (head, describe, iloc, loc ...))
3. Matplotlib (створити набір даних лінійної функції з урахуванням помилок вимірювань, побудувати графік функції та згенерованих даних, обчислити похибку з використанням метрик MAE, MSE). Записати отримані результати у csv файл (формат: X,Y, Y_hat, mAE, mSE)

4. Відповіді оформити .ipynb документом
5. Викласти у зазначений репозіторій GitHub в окремій папці з назвою Lab1 де має бути .ipynb файл та необхідні файли з даними

In [11]:
import numpy as np
import pandas as pd
import matplotlib as mpl

print("CRUD operations")
print("Creation: ")
array1 = np.arange(0,100,5)
print(array1) 
array2 = np.random.randint(0, 100, 20)
print(array2)
print("Add element in the end of array2: ")
array2 = np.append(array2, 20)
print(array2, end='\n\n')


print("Reading last element of second array:")
print(array2.item(array2.size-1), end="\n\n")

print("Updating: changed array1 1st element to 777")
array1[0] = 777
print(array1, end="\n\n")

print("Deleting: delete array2 1st element")
array2 = np.delete(array2, 0)
print(array2, end="\n\n")

print("Scalar: ")
array1 = np.multiply(array1, 1.7)
print(array1)
array2 = np.power(array2, 2)
print(array2, end="\n\n")

print("Vector: ")
array12 = np.add(array1,array2)
array13 = np.subtract(array1,array2)
print(array12)
print(array13, end="\n\n")

print("Matrix: ")
mat1 = np.random.randint(0, 100, size = (5,5))
print(mat1, sep="\n")

CRUD operations
Creation: 
[ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]
[74 56 64 21 79 59 83 31 62 16 83 39 55 31 91 91 81 76 87 40]
Add element in the end of array2: 
[74 56 64 21 79 59 83 31 62 16 83 39 55 31 91 91 81 76 87 40 20]

Reading last element of second array:
20

Updating: changed array1 1st element to 777
[777   5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85
  90  95]

Deleting: delete array2 1st element
[56 64 21 79 59 83 31 62 16 83 39 55 31 91 91 81 76 87 40 20]

Scalar: 
[1320.9    8.5   17.    25.5   34.    42.5   51.    59.5   68.    76.5
   85.    93.5  102.   110.5  119.   127.5  136.   144.5  153.   161.5]
[3136 4096  441 6241 3481 6889  961 3844  256 6889 1521 3025  961 8281
 8281 6561 5776 7569 1600  400]

Vector: 
[4456.9 4104.5  458.  6266.5 3515.  6931.5 1012.  3903.5  324.  6965.5
 1606.  3118.5 1063.  8391.5 8400.  6688.5 5912.  7713.5 1753.   561.5]
[-1815.1 -4087.5  -424.  -6215.5 -3447.  -6846.5  -910.  -3784.5  -188.