#Лабораторна робота 1
###Студента групи МІТ-31 (підгрупа 2)
###Луніна Леоніда Олександровича

##Завдання
1. NumPy (створити набір даних (розмір за власним рішенням), провести CRUD операції над даними (скаляр, вектор, матриця)). Використати arange, random.
2. Pandas (створити dataframe різними способами, провести маніпуляції з даними (head, describe, iloc, loc ...))
3. Matplotlib (створити набір даних лінійної функції з урахуванням помилок вимірювань, побудувати графік функції та згенерованих даних, обчислити похибку з використанням метрик MAE, MSE). Записати отримані результати у csv файл (формат: X,Y, Y_hat, mAE, mSE)

4. Відповіді оформити .ipynb документом
5. Викласти у зазначений репозіторій GitHub в окремій папці з назвою Lab1 де має бути .ipynb файл та необхідні файли з даними

In [2]:
import numpy as np

print("CRUD operations with numbers")
x = 5
y = 7
print("x = ", x)
print("y = ", y)
print("x+y = ", x+y)
print("x-y = ", x-y)
print("x*y = ", x*y)
print("x/y = ", x/y)



print()
print("CRUD operations with array")
print("Creation: ")
array1 = np.arange(0,100,5)
print(array1) 
array2 = np.random.randint(0, 100, 20)
print(array2)
print("Add element in the end of array2: ")
array2 = np.append(array2, 20)
print(array2, end='\n\n')


print("Reading last element of second array:")
print(array2.item(array2.size-1), end="\n\n")

print("Updating: changed array1 1st element to 777")
array1[0] = 777
print(array1, end="\n\n")

print("Deleting: delete array2 1st element")
array2 = np.delete(array2, 0)
print(array2, end="\n\n")

print("Scalar: ")
array1 = np.multiply(array1, 1.7)
print(array1)
array2 = np.power(array2, 2)
print(array2, end="\n\n")

print("Vector: ")
array12 = np.add(array1,array2)
array13 = np.subtract(array1,array2)
print(array12)
print(array13, end="\n\n")

mat1 = np.random.randint(1, 100, size = (5,5))
mat2 = np.random.randint(1, 100, size = (5,5))
print("Matrix 1: ")
print(mat1, sep="\n\n")
print("Matrix 2: ")
print(mat2, sep="\n\n")

print("+: ")
print(mat1+mat2)
print("-: ")
print(mat1-mat2)
print("*: ")
print(mat1*mat2)
print("/: ")
print(mat1/mat2)

CRUD operations with numbers
x =  5
y =  7
x+y =  12
x-y =  -2
x*y =  35
x/y =  0.7142857142857143

CRUD operations with array
Creation: 
[ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]
[49 83 10 50 94 40 73  0 21 43  3 52 67 50 29 18 92  6 32 43]
Add element in the end of array2: 
[49 83 10 50 94 40 73  0 21 43  3 52 67 50 29 18 92  6 32 43 20]

Reading last element of second array:
20

Updating: changed array1 1st element to 777
[777   5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85
  90  95]

Deleting: delete array2 1st element
[83 10 50 94 40 73  0 21 43  3 52 67 50 29 18 92  6 32 43 20]

Scalar: 
[1320.9    8.5   17.    25.5   34.    42.5   51.    59.5   68.    76.5
   85.    93.5  102.   110.5  119.   127.5  136.   144.5  153.   161.5]
[6889  100 2500 8836 1600 5329    0  441 1849    9 2704 4489 2500  841
  324 8464   36 1024 1849  400]

Vector: 
[8209.9  108.5 2517.  8861.5 1634.  5371.5   51.   500.5 1917.    85.5
 2789.  4582.5 2602.   951.5  44